{
 "title": "4GS Contas",
 "time": { "from": "2024-01-10T00:50:51.678Z", "to": "2024-01-10T01:00:20.495Z" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requisições",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{uri=\"/contas/{id}\"}) by (uri) -\r\n(\r\n    (sum(http_server_requests_seconds_count{uri=\"/contas/{id}\"} offset $__interval) by (uri) > 0 \r\n    or\r\n    ((sum(http_server_requests_seconds_count{uri=\"/contas/{id}\"}) by (uri)) * 0)) > 0\r\n )",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Sucesso",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{uri=\"/contas/{id}\", status=~\"2..\"}) by (uri, status) -\r\n(\r\n    (sum(http_server_requests_seconds_count{uri=\"/contas/{id}\", status=~\"2..\"} offset $__interval) by (uri, status) > 0 \r\n    or\r\n    ((sum(http_server_requests_seconds_count{uri=\"/contas/{id}\", status=~\"2..\"}) by (uri, status)) * 0)) > 0\r\n )",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{uri=\"/contas/{id}\", status=~\"5..\"}) by (uri, status) -\r\n(\r\n    sum(http_server_requests_seconds_count{uri=\"/contas/{id}\", status=~\"5..\"} offset $__interval) by (uri, status) > 0 \r\n    or\r\n    ((sum(http_server_requests_seconds_count{uri=\"/contas/{id}\", status=~\"5..\"}) by (uri, status)) * 0)\r\n )",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Latency GET Conta",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/contas/{id}\"}[$__interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/contas/{id}\"}[$__interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/contas/{id}\"}[$__interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/contas/{id}\"}[$__interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Latency GET Conta",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/contas/{id}\"}[$__range])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/contas/{id}\"}[$__range])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/contas/{id}\"}[$__range])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/contas/{id}\"}[$__range])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "4xx",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{uri=\"/contas/{id}\", status=~\"4..\"}) by (uri, status) -\r\n(\r\n    (sum(http_server_requests_seconds_count{uri=\"/contas/{id}\", status=~\"4..\"} offset $__interval) by (uri, status) > 0 \r\n    or\r\n    ((sum(http_server_requests_seconds_count{uri=\"/contas/{id}\", status=~\"4..\"}) by (uri, status)) * 0)) > 0\r\n )",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "3xx",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{uri=\"/contas/{id}\", status=~\"3..\"}) by (uri, status) -\r\n(\r\n    sum(http_server_requests_seconds_count{uri=\"/contas/{id}\", status=~\"3..\"} offset $__interval) by (uri, status) > 0 \r\n    or\r\n    ((sum(http_server_requests_seconds_count{uri=\"/contas/{id}\", status=~\"3..\"}) by (uri, status)) * 0)\r\n )",
     "legendFormat": "{{outcome}}"
    }
   ]
  }
 ]
}